name: Promote main branch to production
on:
  workflow_dispatch:

jobs:
  rebase:
    name: Rebase and push
    runs-on: ubuntu-latest
    concurrency:
      group: clay-play
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@users.noreply.github.com"
          git fetch --all
          git checkout production
          git rebase main
          git push origin production
        
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
