name: test

on:
  pull_request:
    branches:
      main

jobs:
  test:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Install dependencies
        run: go get ./...
      - name: Test
        run: go test ./...
